import { NextResponse } from 'next/server';

import { getAuthEmail } from '@/lib/auth-utils';
import {
  generateBridgeApiKey,
  generateInstallToken,
  hashInstallToken,
} from '@/lib/bridge-tokens';
import { encrypt } from '@/lib/encryption';
import { createClerkSupabaseClient } from '@/lib/supabase/server';

/**
 * POST /api/bridge-config/generate
 *
 * Creates (or resets) the authenticated user's local-bridge credentials.
 * Returns the install token and bridge API key in plaintext — the client
 * MUST display them immediately and the user MUST paste them into their
 * bridge .env. After this response, the install token is never recoverable
 * (we only store its hash).
 *
 * Calling this again rotates both secrets and invalidates any bridge that
 * was previously registered with the old install token. The old public URL
 * is cleared so the client doesn't attempt to connect to a stale tunnel.
 */
export async function POST() {
  const email = await getAuthEmail();
  if (!email) {
    return NextResponse.json({ error: 'Not authorized' }, { status: 401 });
  }

  const supabase = await createClerkSupabaseClient();
  if (!supabase) {
    return NextResponse.json(
      { error: 'Database not configured' },
      { status: 503 }
    );
  }

  const installToken = generateInstallToken();
  const bridgeApiKey = generateBridgeApiKey();

  const { error } = await supabase.from('bridge_configs').upsert(
    {
      email,
      bridge_url: null,
      api_key_encrypted: encrypt(bridgeApiKey),
      install_token_hash: hashInstallToken(installToken),
      last_seen_at: null,
      updated_at: new Date().toISOString(),
    },
    { onConflict: 'email' }
  );

  if (error) {
    console.error('bridge_configs upsert error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  const webOrigin = process.env.NEXT_PUBLIC_APP_URL || '';

  const envTemplate = [
    '# Anubix Bridge — generated by anubix-web',
    `ANUBIX_INSTALL_TOKEN=${installToken}`,
    `BRIDGE_API_KEY=${bridgeApiKey}`,
    webOrigin ? `ANUBIX_WEB_URL=${webOrigin}` : '# ANUBIX_WEB_URL=https://your-anubix-web.example.com',
    'TUNNEL_MODE=auto',
    'CLAUDE_MODE=cli',
    'PORT=3456',
  ].join('\n');

  return NextResponse.json({
    installToken,
    bridgeApiKey,
    envTemplate,
  });
}
